apiVersion: v1
kind: ConfigMap
metadata:
  name: email-conf
  labels:
    {{- include "gomall.labels" . | nindent 4 }}
    app.kubernetes.io/component: email
data:
  conf.yaml: |
    kitex:
      service: "{{ .Values.email.kitex.service }}"
      address: "{{ .Values.email.kitex.address }}"
      log_level: {{ .Values.email.kitex.log_level }}
    nats:
      url: "{{ .Values.email.nats.url }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
  labels:
    {{- include "gomall.labels" . | nindent 4 }}
    app.kubernetes.io/component: email
spec:
  replicas: {{ .Values.email.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gomall.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: email
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gomall.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: email
    spec:
      containers:
      - name: email
        image: "{{ .Values.email.image.repository }}:{{ .Values.email.image.tag }}"
        ports:
        - containerPort: {{ .Values.email.service.targetPort }}
        env:
        - name: GO_ENV
          value: {{ .Values.global.goEnv | quote }}
        volumeMounts:
        - name: conf
          mountPath: /app/conf/{{ .Values.global.goEnv }}/conf.yaml
          subPath: conf.yaml
      volumes:
      - name: conf
        configMap:
          name: email-conf
---
apiVersion: v1
kind: Service
metadata:
  name: email
  labels:
    {{- include "gomall.labels" . | nindent 4 }}
    app.kubernetes.io/component: email
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.email.service.port }}
    targetPort: {{ .Values.email.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ include "gomall.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: email
