{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-conf
  labels:
    {{- include "gomall.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
data:
  conf.yaml: |
    hertz:
      address: "{{ .Values.frontend.hertz.address }}"
      metrics_port: {{ .Values.frontend.hertz.metrics_port }}
      enable_pprof: {{ .Values.frontend.hertz.enable_pprof }}
      enable_gzip: {{ .Values.frontend.hertz.enable_gzip }}
      enable_access_log: {{ .Values.frontend.hertz.enable_access_log }}
      log_level: {{ .Values.frontend.hertz.log_level }}
    redis:
      address: "{{ .Values.frontend.redis.address }}"
      username: "{{ .Values.frontend.redis.username }}"
      password: "{{ .Values.frontend.redis.password }}"
      db: {{ .Values.frontend.redis.db }}
    session_secret: {{ .Values.frontend.session_secret | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    {{- include "gomall.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gomall.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gomall.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        ports:
        - containerPort: {{ .Values.frontend.service.targetPort }}
        env:
        - name: GO_ENV
          value: {{ .Values.global.goEnv | quote }}
        volumeMounts:
        - name: conf
          mountPath: /app/conf/{{ .Values.global.goEnv }}/conf.yaml
          subPath: conf.yaml
      volumes:
      - name: conf
        configMap:
          name: frontend-conf
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    {{- include "gomall.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ include "gomall.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
{{- end }}
